import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { getServerSession } from 'next-auth';
import { ThemeProvider } from 'next-themes';
import GlobalHeader from '@/components/header';
import SessionProviderClient from './components/SessionProviderClient';
import 'react-image-crop/dist/ReactCrop.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // choose the weights you need
  variable: '--font-poppins', // optional for Tailwind
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} antialiased font-nunito-sans font-nunito `}>
        <SessionProviderClient session={session}>
          <ThemeProvider attribute="class" defaultTheme="light" forcedTheme="light" disableTransitionOnChange>
            <main>
              {session?.user && (
                <section>
                  <GlobalHeader />
                </section>
              )}
              <section>{children}</section>
            </main>
          </ThemeProvider>
        </SessionProviderClient>
      </body>
    </html>
  );
}

